### ISSUE TITLE
Implement Cotton's truncated Davidson

### ISSUE THREAD

**Issue by susilehtola** [wavefunction91/MACIS#23]
In [J. Chem. Phys. 157, 224105 (2022)](https://doi.org/10.1063/5.0115796), Cotton describes a truncated Davidson technique which rapidly converges to the exact answer.

**Comment by wavefunction91** [comment]
If this were to be implemented (which it won't because it's a poorly formulated method with little practical justification), it would belong in the upcoming refactor to include the generic solver project we're developing.
